spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:9080/auth/realms/ssq
        registration:
          oidc:
            client-id: ssq-registry
            client-secret: ssq-registry

server:
  servlet:
    session:
      cookie:
        http-only: true
        # custom session cookie name to prevent conflict with another application on the same domain
        name: JSESSIONID_REGISTRY
